Refactor market keeper against master
e-money/em-ledger pull request #150
Opened 2021-09-27 14:45 UTC by blewater

- Closes [#135](https://github.com/e-money/em-ledger/issues/135) remove the returned sdk.Result from the Keeper API.
- Sets the context's event manager to return events.
- Added missing error descriptions.
- Added `add-market`, `cancelreplace` order type bdd tests.
- Added bdd test market order event validation.

2021-09-29 12:04 UTC, haasted requested changes

2021-09-29 13:43 UTC, blewater commented on market_test.go
> +	Expect(foundAccept).To(BeTrue(), "did not find the accept event")
there's an extra boolean condition `&& ...`
The flow falls to the `expect` statements when it did not find the `fill` when it should be and affirm the accept was found and the opposite case `accept` was there but the `fill`...

2021-09-30 10:24 UTC, haasted commented on x/market/keeper/keeper.go
> +		retEvManager.EmitEvents(ctx.EventManager().Events())
If it always needs to happen, it can be placed outside the deferred function.

2021-09-30 10:50 UTC, blewater commented on x/market/keeper/keeper.go
> +		retEvManager.EmitEvents(ctx.EventManager().Events())
outside the defer would miss events when returning on errors

2021-09-30 11:01 UTC, haasted commented on x/market/keeper/keeper.go
> +		retEvManager.EmitEvents(ctx.EventManager().Events())
The function is actually divided into two: Precondition checks, which may return errors, and "order accepted" which runs the rest of the function. After order accepted, there is no return statements until the end of the function.

2021-09-30 11:31 UTC, blewater commented on x/market/keeper/keeper.go
> +		retEvManager.EmitEvents(ctx.EventManager().Events())
Moved it before return.

2021-09-30 12:01 UTC, haasted approved these changes

2021-09-30 12:02 UTC, merged