#51 free liquidity -- Draft PR
e-money/em-ledger pull request #66
Opened 2021-05-18 15:50 UTC by blewater

Please note, changesets from previous open PRs have crept in.
### A. Draft PR for soliciting feedback on completed 1..4 issue items.

> 1. Make the gas associated with all market messages identical, so that MsgCancelLimitOrder potentially carries same cost as MsgCancelReplaceLimitOrder.
> 2. New orders that add liquidity should receive a gas rebate proportional to how much of the order was filled already (0% fill means 100% rebate):
> https://github.com/e-money/em-ledger/blob/12b0302ca45100ddeaebfd882392b4731ff16837/x/market/keeper/keeper.go#L334
> 3. Canceled orders always pay full gas.
> 4. Replaced orders are only eligible for the gas rebate in 2. if they are replacing an order older than, say, 5 minutes. This requires #34 to work.

### B. This PR does not address issue section: ```Additional considerations```. 
Suggestions below

> It must not be possible to exploit the rebate mechanism in a way where it becomes cheaper (or even free) to remove liquidity, i.e. crafting an order to get almost filled but adding a small amount to the book should not result in a rebate.
> It must not be possible to spam the chain with useless transactions. Only behaviour that is net adding liquidity

#### Half baked ideas

1. Make Liquidity Fee a minimal dust amount i.e. 250 resulting in *free* single transactions, but costly for sending a large number of transactions. A known practice.
2. Do not rebate more than x number of *free* liquid orders per account at any time. *Not a great solution in isolation.*
3. Do not rebate more than x number of duplicate instruments orders per account at any time.
4. Do not rebate any duplicate instrument order that does not offer qty/pricing spread differential above a threshold i.e. the moving average of the last x booked instruments orders + 15%.

### C. Three Market parameters have been added

- May leave them like that (beginblock)
- Add them to genesis
- Const them (what if we change them?)

```Proto
message TxParams {
  // default fee for a market transaction.
  uint64 trx_fee = 1;

  // Valid liquidity adding orders are free(0) or set to this minimal fee
  uint64 liquid_trx_fee = 2;

  // Minutes interval for eligible replacing transactions to receive a rebate.
  // For a rebate to apply, the replacing transaction should occur these minutes
  // after the signer's original trx.
  int64 liquidity_rebate_minutes_span = 3;
}
```

2021-05-20 10:28 UTC, haasted requested changes

2021-05-20 11:23 UTC, blewater commented on x/market/keeper/keeper.go
> +	if order.TimeInForce == types.TimeInForce_FillOrKill {
thank you Sir!

2021-06-02 09:10 UTC, blewater commented on x/market/keeper/keeper.go
> +	if orderErr := recover(); orderErr != nil {
Removed recover()

2021-06-02 09:11 UTC, blewater commented on x/market/types/market.pb.go
> +	OrigOrderCreated time.Time `protobuf:"bytes,11,opt,name=orig_order_created,json=origOrderCreated,proto3,stdtime" json:"orig_order_created" yaml:"orig_order_created"`
Removed the field.

2021-06-02 09:11 UTC, blewater commented on x/market/keeper/keeper.go
> +func (k *Keeper) calcReplaceOrderGas(
Done

2021-06-02 09:35 UTC, blewater commented
### Freezing this feature while a better SDK or an alternative solution is found.
Accomplished in this work are predictable gas costs for market orders **within the market module**.
However, before entering the market order, RunTx() spends gas outside within the Ante handlers chain, which in the DeliverTx tests they ramp up to ~55000. These can be zeroed out with an extra ante handler for the market module but at the severe disadvantage of exposing a security vulnerability of gas-free transactions when the market module panics.

A solution explored for mitigating the security vulnerability is adding a BaseApp custom panic handler, combined with the handler having access to the transaction gas meter for charging a gas fee which sadly it does not. As a future consideration, we could open an issue with the Cosmos SDK team to add gas meter access to panic-handlers applicable to this and other business functionality.

2021-06-02 09:35 UTC, closed without merging

2021-06-07 09:34 UTC, blewater commented
There is a completed Cosmos SDK PR that meets the needs of this functionality, and it was stalled because of a lack of an accompanied ADR. We could pick up the pieces for this and contribute the ADR and facilitate the re-opening of the stalled PR to complete this [add gas refund handler to refund the remaining gas fee at the end of transaction #8993](https://github.com/cosmos/cosmos-sdk/pull/8993).